version: '3.7'

volumes:
  neo4j_data:
  tfgpu_jupyter:

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
  
services:
  stanford_corenlp:
    image: d1egoprog/stanford-corenlp:4.1.0
    ports:
      - "9000:9000"
    networks: 
      backend:
        ipv4_address: 172.18.0.102
    restart: always
  neo4j_server:
    image: neo4j:4.2.4
    networks: 
      backend:
        ipv4_address: 172.18.0.103
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/conf
      - neo4j_data:/data
      - neo4j_data:/logs
      - neo4j_data:/plugins
    environment: 
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=["n10s"]
    restart: always
  triple_api:
    image: d1egoprog/triple-operations:1.0
    ports:
      - "5050:5000"
    networks: 
      backend:
        ipv4_address: 172.18.0.101
    depends_on:
      - "stanford_corenlp"
      - "neo4j_server"
    restart: always
  tfgpu_jupyter:
    image: d1egoprog/tensorflow-gpu-jupyter:1.15.4-lab
    ports:
      - "9988:8888"
    volumes:
      - tfgpu_jupyter:/home/jupyter/notebooks
      - tfgpu_jupyter:/home/jupyter/data
      - ./examples/:/home/jupyter/text2kg/
    depends_on:
      - "triple_api"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    networks: 
      backend:
        ipv4_address: 172.18.0.104
    restart: always
